/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tic.tac.game;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();       
        ImageIcon image = new ImageIcon("E:\\Courses\\Java Course\\Projects\\Tic Tac game\\Tic Tac game\\src\\tic\\tac\\game\\logo.jpg");
        this.setIconImage(image.getImage());
        jLabel2.setFont(new Font("MV Boli", Font.PLAIN, 42));
        jLabel2.setForeground(new Color(160, 220, 230));
        xlabel.setFont(new Font(null, Font.BOLD, 38));
        olabel.setForeground(new Color(100, 240, 0));
        olabel.setFont(new Font(null, Font.BOLD, 38));
        jLabel5.setFont(new Font("MV Boli", Font.PLAIN, 37));
        jLabel5.setForeground(new Color(0, 230, 230));
        easy.setFocusable(false);
        medium.setFocusable(false);
        hard.setFocusable(false);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        olabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        xlabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        easy = new button.mybutton();
        medium = new button.mybutton();
        hard = new button.mybutton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("choose player");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 550, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,70));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        olabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        olabel.setText("O");
        olabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(olabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(olabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 120, 100, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255,80));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        xlabel.setForeground(new java.awt.Color(255, 255, 255));
        xlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xlabel.setText("X");
        xlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 120, 100, 80));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Choose level ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 550, 50));

        easy.setBorder(null);
        easy.setForeground(new java.awt.Color(56, 57, 255));
        easy.setText("Easy");
        easy.setBorderColor(new java.awt.Color(255, 255, 255));
        easy.setBorderPainted(false);
        easy.setColorClick(new java.awt.Color(102, 255, 255));
        easy.setColorOver(new java.awt.Color(51, 255, 255));
        easy.setColorText(new java.awt.Color(255, 255, 255));
        easy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        easy.setRadius(9);
        easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyActionPerformed(evt);
            }
        });
        jPanel1.add(easy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, 50));

        medium.setBorder(null);
        medium.setForeground(new java.awt.Color(56, 57, 255));
        medium.setText("Medium");
        medium.setBorderColor(new java.awt.Color(255, 255, 255));
        medium.setBorderPainted(false);
        medium.setColorClick(new java.awt.Color(102, 255, 255));
        medium.setColorOver(new java.awt.Color(51, 255, 255));
        medium.setColorText(new java.awt.Color(255, 255, 255));
        medium.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        medium.setRadius(9);
        medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumActionPerformed(evt);
            }
        });
        jPanel1.add(medium, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 100, 50));

        hard.setBorder(null);
        hard.setForeground(new java.awt.Color(56, 57, 255));
        hard.setText("Hard");
        hard.setBorderColor(new java.awt.Color(255, 255, 255));
        hard.setBorderPainted(false);
        hard.setColorClick(new java.awt.Color(102, 255, 255));
        hard.setColorOver(new java.awt.Color(51, 255, 255));
        hard.setColorText(new java.awt.Color(255, 255, 255));
        hard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hard.setRadius(9);
        hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardActionPerformed(evt);
            }
        });
        jPanel1.add(hard, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ff.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 2, 560, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        jPanel3.setBackground(new Color(190, 241, 234)); //panel x
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jPanel2.setBackground(new Color(30, 140, 30)); // panel o
    }//GEN-LAST:event_jPanel2MouseClicked

    private void xlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xlabelMouseClicked
        // X label
        jPanel3.setBackground(new Color(180, 180, 220));
        TicTacGame.HUMAN = 'X';
        TicTacGame.AI = 'O';
    }//GEN-LAST:event_xlabelMouseClicked

    private void olabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olabelMouseClicked
        //O label
        jPanel2.setBackground(new Color(30, 140, 30));
        TicTacGame.HUMAN = 'O';
        TicTacGame.AI = 'X';
    }//GEN-LAST:event_olabelMouseClicked

    private void easyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyActionPerformed

        TicTacGame.depth = 3;
        new player().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_easyActionPerformed

    private void mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumActionPerformed

        TicTacGame.depth = 4;
        new player().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mediumActionPerformed

    private void hardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardActionPerformed
        TicTacGame.depth = 10;
        new player().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hardActionPerformed

    private void xlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xlabelMouseExited
    }//GEN-LAST:event_xlabelMouseExited

    private void xlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xlabelMouseEntered
    }//GEN-LAST:event_xlabelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.mybutton easy;
    private button.mybutton hard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private button.mybutton medium;
    private javax.swing.JLabel olabel;
    private javax.swing.JLabel xlabel;
    // End of variables declaration//GEN-END:variables
}
